
- name: Bridge | Identify Network Interfaces
  debug:
    msg: "Raspberry pi has these interfaces: {{ ansible_interfaces }}"
  register: has_external_wifi_interface

- name: Bridge | Identify wlan1 interface | exists
  debug:
    msg: "Since wlan1 exists, setting up bridge between wlan0 and wlan1"
  when: "'wlan1' in ansible_interfaces"

- fail:
    msg: "wlan1 exists, but no connection data provided, please pass ssid_name/ssid_pass variables"
  when: "'wlan1' in ansible_interfaces and (ssid_name is undefined or ssid_pass is undefined)"

- name: Bridge | Identify wlan1 interface | not exists
  debug:
    msg: "Since wlan1 does not exist, setting up bridge between wlan0 and eth0"
  when: "'wlan1' not in ansible_interfaces"

- name: Bridge | Update and upgrade apt packages
  apt:
    upgrade: 'yes'
    update_cache: yes

- name: Bridge | Install requiered packages
  apt:
    pkg: ['bridge-utils']
    state: latest

- name: Access Point | Set sysctl.conf file
  template:
    src: sysctl.conf.j2
    dest: /etc/sysctl.conf
    owner: root
    group: root
    mode: 644

- name: Bridge | Update iptables with eth0
  shell: iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
  when: "'wlan1' not in ansible_interfaces"

- name: Bridge | Update iptables with wlan1
  shell: iptables -t nat -A POSTROUTING -o wlan1 -j MASQUERADE
  when: "'wlan1' in ansible_interfaces"

- name: Bridge | Update iptables
  shell: sh -c "iptables-save > /etc/iptables.ipv4.nat"

- name: Bridge | Set rc.local file
  template:
    src: rc.local.j2
    dest: /etc/rc.local
    owner: root
    group: root
    mode: 733

- name: Bridge | Set wpa_supplicant.conf file
  template:
    src: wpa_supplicant.conf.j2
    dest: /etc/wpa_supplicant/wpa_supplicant.conf
    owner: root
    group: root
    mode: 600
  when: "'wlan1' in ansible_interfaces"

- name: Bridge | Set interfaces file
  template:
    src: network_interfaces.j2
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: 644
  when: "'wlan1' in ansible_interfaces"

- name: Bridge | Reboot the machine
  reboot:
