---
  - name: Restart | Reboot the machine
    reboot:
        reboot_timeout: 180

  #- name: Restart | Wait 180 seconds, but only start checking after 30 seconds
  #  wait_for_connection:
  #      delay: 30
  #      timeout: 180

  - name: Restart | Get up time
    ansible.builtin.shell: uptime
    register: up_time

  - name: Restart | Get kernel version
    ansible.builtin.shell: uname -sr
    register: kernel

  - name: Restart | Just print command output
    ansible.builtin.debug:
        msg:
            - "System is up and running from {{ up_time.stdout }}"
            - "System kernel version is {{ kernel.stdout }}"