
- name: Extender | Install requiered packages
  apt:
    pkg: ['bridge-utils']
    state: latest

- name: Extender | Set interfaces file
  template:
    src: network_interfaces_bridge.j2
    dest: /etc/network/interfaces.d/raspberry_interfaces
    owner: root
    group: root
    mode: 644