
- name: Setup Raspberry PI Repeater
  hosts: all
  become: true

  vars:
    extended_network: False

#  vars_prompt:
#    - name: ap_ssid_name
#      prompt: "Enter SSID for access point setup"
#      private: no
#    - name: ap_ssid_pass
#      prompt: "Enter password for access point setup"
#      private: no

  pre_tasks:
    - name: Fail job if not supported setup
      fail:
        msg: "Extended network when bridging between two wireless interfaces is not currently supported, extended network must be connected to eth0 and wlan0"
      when: "'wlan1' in ansible_interfaces and extended_network"

  roles:
    - setup_raspberry_access_point
    - setup_raspberry_dhcpcd
    - { role: "setup_raspberry_extender", when: (extended_network | bool) }
    - { role: "setup_raspberry_repeater", when: (not extended_network | bool) }
    - reboot_raspberry