
- name: Access Point | Identify Network Interfaces
  debug:
    msg: "Raspberry pi has these interfaces: {{ ansible_interfaces }}"

- name: Access Point | Fail job if wlan0 not detected
  fail:
    msg: "wlan0 does not exists, please check raspberry pi onboard wifi card/wifi dongle"
  when: "'wlan0' not in ansible_interfaces"

- name: Access Point | Update and upgrade apt packages
  apt:
    upgrade: 'yes'
    update_cache: yes

- name: Access Point | Install requiered packages
  apt:
    pkg: ['hostapd']
    state: latest

- name: Access Point | Stop hostapd, if running
  systemd:
    name: "{{ item }}.service"
    state: stopped
  with_items:
    - hostapd

- name: Access Point | Set hostapd.conf file
  template:
    src: hostapd.conf.j2
    dest: /etc/hostapd/hostapd.conf
    owner: root
    group: root
    mode: 644

- name: Access Point | Set hostapd daemon file
  template:
    src: hostapd_daemon.j2
    dest: /etc/default/hostapd
    owner: root
    group: root
    mode: 644

- name: Access Point | Check if hostapd service -> /dev/null exists
  stat:
    path: /etc/systemd/system/hostapd.service
  register: hostapd_link_exists

- name: Access Point | Remove hostapd service -> /dev/null link
  file:
    path: /etc/systemd/system/hostapd.service
    state: absent
  when: hostapd_link_exists.stat.exists

- name: Access Point | Unblock wlan
  shell: rfkill unblock wlan

- name: Access Point | Restart hostapd and enable
  systemd:
    state: restarted
    daemon_reload: yes
    name: "{{ item }}.service"
    enabled: yes
    masked: no
  with_items:
    - hostapd